// src/styles.js

const Styles = {
  container: {
    fontFamily: 'Inter, Arial, sans-serif',
    backgroundColor: '#ebeff2',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    padding: '0 0px 0px 0px',
    paddingTop: '0px',
    paddingBottom: '90px',
    overflowY: 'auto',
    flexGrow: 1,
  },
  appTitle: {
    color: '#2c3e50',
    marginBottom: '20px',
    fontSize: '28px',
    fontWeight: '700',
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: '#045271',
    color: 'white',
    padding: '10px 35px',
    border: 'none',
    borderRadius: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '30px',
    marginBottom: '20px',
    boxShadow: '0 6px 15px rgba(4, 82, 113, 0.4)',
    transition: 'background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease',
    outline: 'none',
    width: '100%',
    maxWidth: '150px',
  },
  sectionsContainer: {
    width: '100%',
  },
  medicalSection: {
    backgroundColor: '#ffffff',
    padding: '25px',
    marginBottom: '5px', // Se mantiene el valor que me proporcionaste
    boxShadow: '0 4px 12px rgba(204, 226, 252, 0.06)',
    width: '100%',
    boxSizing: 'border-box',
  },
  sectionTitle: {
    color: '#000000',
    fontSize: '16px',
    marginBottom: '15px',
    fontWeight: '600',
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    flexWrap: 'nowrap',
    width: '100%',
  },
  textArea: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 'auto',
    padding: '12px',
    borderRadius: '10px',
    border: '1px solid #e0e0e0',
    fontSize: '16px',
    resize: 'vertical',
    minHeight: '80px',
    boxShadow: 'inset 0 1px 3px rgba(0,0,0,0.05)',
    width: '100%',
    boxSizing: 'border-box',
    minWidth: '0',
  },
  micButton: {
    flexShrink: 0,
    backgroundColor: ' #0e77e8',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    width: '60px',
    height: '60px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '30px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0,123,255,0.4)',
    transition: 'background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease',
    minWidth: '0',
  },
  micButtonActive: {
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    width: '65px',
    height: '65px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '32px',
    cursor: 'pointer',
    boxShadow: '0 6px 15px rgba(220,53,69,0.5)',
    transform: 'scale(1.05)',
  },
  errorText: {
    color: '#dc3545',
    fontSize: '14px',
    marginTop: '10px',
    textAlign: 'center',
  },
  // --- ESTILOS PARA EL MODAL ---
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '10px',
    boxShadow: '0 5px 15px rgba(0, 0, 0, 0.3)',
    textAlign: 'center',
    maxWidth: '350px',
    width: '90%',
  },
  modalMessage: {
    fontSize: '18px',
    marginBottom: '20px',
    color: '#333',
  },
  modalActions: { // Nuevo estilo para el contenedor de botones del modal
    display: 'flex',
    justifyContent: 'center',
    gap: '15px',
    marginTop: '10px',
  },
  modalButton: {
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '16px',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: '#0056b3',
    },
  },
  modalButtonCancel: { // Estilo específico para el botón de cancelar
    backgroundColor: '#6c757d',
    '&:hover': {
      backgroundColor: '#5a6268',
    },
  },
  modalButtonConfirm: { // Estilo específico para el botón de confirmar
    backgroundColor: '#28a745',
    '&:hover': {
      backgroundColor: '#218838',
    },
  },
  // --- FIN ESTILOS PARA EL MODAL ---
  specialtySelectContainer: {
    backgroundColor: '#ffffff',
    padding: '25px',
    marginBottom: '20px',
    width: '100%',
    maxWidth: '550px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.06)',
  },
  specialtySelectTitle: {
    color: '#34495e',
    fontSize: '20px',
    marginBottom: '15px',
    fontWeight: '600',
  },

  navbar: {
    backgroundColor: 'rgb(0, 120, 245)',
    padding: '10px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    boxShadow: '0 2px 5px rgba(0,0,0,0.2)',
    position: 'sticky',
    top: 0,
    zIndex: 500,
  },
  navbarBrand: {
    color: 'white',
    fontSize: '24px',
    fontWeight: 'bold',
    textDecoration: 'none',
  },
  navbarNav: {
    display: 'flex',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  navItem: {
    marginLeft: '20px',
  },
  navLink: {
    color: 'white',
    textDecoration: 'none',
    padding: '8px 12px',
    borderRadius: '8px',
    transition: 'background-color 0.3s ease',
    fontSize: '16px',
    fontWeight: '500',
  },
  navLinkActive: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    fontWeight: 'bold',
  },
  hamburgerMenu: {
    display: 'none',
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: '30px',
    cursor: 'pointer',
  },
  drawer: {
    position: 'fixed',
    top: 0,
    right: 0,
    width: '250px',
    height: '100%',
    backgroundColor: '#34495e',
    boxShadow: '-5px 0 15px rgba(0,0,0,0.3)',
    transform: 'translateX(100%)',
    transition: 'transform 0.3s ease-in-out',
    zIndex: 900,
    paddingTop: '60px',
  },
  drawerOpen: {
    transform: 'translateX(0)',
  },
  drawerCloseButton: {
    position: 'absolute',
    top: '15px',
    right: '15px',
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: '30px',
    cursor: 'pointer',
  },
  drawerNavList: {
    listStyle: 'none',
    padding: '0',
    margin: '0',
  },
  drawerNavItem: {
    padding: '10px 20px',
    borderBottom: '1px solid rgba(255,255,255,0.1)',
  },
  drawerNavLink: {
    color: 'white',
    textDecoration: 'none',
    fontSize: '18px',
    display: 'block',
    padding: '10px 0',
    transition: 'background-color 0.3s ease',
  },
  '@media (max-width: 768px)': {
    navbarNav: {
      display: 'none',
    },
    hamburgerMenu: {
      display: 'block',
    },
  },

  autocompleteContainer: {
    position: 'relative',
    marginBottom: '20px',
    width: '100%',
  },
  autocompleteLabel: {
    display: 'block',
    fontSize: '18px',
    fontWeight: '600',
    color: '#34495e',
    marginBottom: '10px',
  },
  autocompleteInputWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'nowrap',
    position: 'relative',
  },
  autocompleteInput: {
    flexGrow: 1,
    padding: '12px',
    paddingRight: '40px',
    borderRadius: '10px',
    border: '1px solid #e0e0e0',
    fontSize: '16px',
    boxShadow: 'inset 0 1px 3px rgba(0,0,0,0.05)',
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    width: '100%',
    boxSizing: 'border-box',
    minWidth: '0',
  },
  clearInputButton: {
    position: 'absolute',
    right: '65px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    color: '#999',
    cursor: 'pointer',
    padding: '0 5px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    transition: 'color 0.2s ease',
    zIndex: 10,
    '&:hover': {
      color: '#333',
    },
  },
  autocompleteSuggestionsList: {
    position: 'absolute',
    top: 'calc(100% + 5px)',
    left: 0,
    right: 0,
    backgroundColor: 'white',
    border: '1px solid #ddd',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
    listStyle: 'none',
    padding: '0',
    margin: '0',
    maxHeight: '200px',
    overflowY: 'auto',
    zIndex: 500,
  },
  autocompleteSuggestionItem: {
    padding: '10px 15px',
    fontSize: '16px',
    color: '#333',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
  },
  autocompleteSuggestionItemHighlighted: {
    backgroundColor: '#e0e0e0',
  },

  pageHeaderContainer: {
    position: 'fixed',
    top: '0px',
    left: 0,
    width: '100%',
    zIndex: 400,
    backgroundColor: '#f8f9fa',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  pageHeader: {
    width: '100%',
    backgroundColor: 'rgb(0, 120, 245)',
    padding: '10px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 400,
  },
  pageHeaderBackButton: {
    position: 'absolute',
    left: '20px',
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: '30px',
    cursor: 'pointer',
  },
  pageHeaderTitle: {
    color: 'white',
    fontSize: '16px',
    fontWeight: 'bold',
    margin: 0,
  },
  patientSummaryCard: {
    backgroundColor: 'rgb(231, 241, 248)',
    borderRadius: '1px',
    padding: '8px 20px',
    marginBottom: '0px', // Se mantiene el valor que me proporcionaste
    width: '100%',
    boxShadow: '0 2px 5px hsla(220, 33.30%, 98.20%, 0.05)',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  patientSummaryName: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: '5px',
  },
  patientSummaryDetails: {
    fontSize: '14px',
    color: '#666',
  },
  iconicButtonsContainer: {
    display: 'none',
  },
  iconicButton: {
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '15px 10px',
    width: '90px',
    height: '90px',
    boxShadow: '0 2px 8px hsla(212, 62.10%, 54.50%, 0.10)',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    textDecoration: 'none',
    color: '#333',
  },
  iconicButtonActive: {
    backgroundColor: '#e0f7fa',
    boxShadow: '0 4px 12px rgba(0,123,255,0.2)',
    transform: 'translateY(-2px)',
  },
  iconicButtonIcon: {
    fontSize: '30px',
    color: '#007bff',
    margin: 0,
    lineHeight: '1em',
  },
  iconicButtonText: {
    fontSize: '12px',
    textAlign: 'center',
    fontWeight: '600',
    margin: 0,
    lineHeight: '1em',
  },
  listItemCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '15px',
    marginBottom: '10px',
    boxShadow: '0 2px 6px rgba(0,0,0,0.05)',
    borderLeft: '5px solid #007bff',
  },
  listItemCardTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: '5px',
  },
  listItemCardSubtitle: {
    fontSize: '14px',
    color: '#666',
  },

  structuredInputContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
    flexWrap: 'nowrap',
  },
  processButton: {
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 15px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    marginTop: '10px',
    width: '100%',
  },
  structuredList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    marginTop: '15px',
  },
  structuredListItem: {
    backgroundColor: '#f2f4f6',
    borderRadius: '8px',
    padding: '12px 15px',
    marginBottom: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  listItemText: {
    fontSize: '15px',
    color: '#333',
  },
  listItemActions: {
    display: 'flex',
    gap: '8px',
    marginTop: '5px',
  },
  listItemButton: {
    background: 'none',
    border: 'none',
    fontSize: '14px',
    cursor: 'pointer',
    color: '#007bff',
    padding: '5px',
    borderRadius: '5px',
    transition: 'background-color 0.2s ease',
  },
  listItemButtonDelete: {
    color: '#dc3545',
  },
  itemEditModalContent: {
    backgroundColor: 'white',
    padding: '25px',
    borderRadius: '10px',
    boxShadow: '0 5px 15px rgba(0, 0, 0, 0.3)',
    textAlign: 'left',
    maxWidth: '400px',
    width: '90%',
  },
  itemEditModalTitle: {
    fontSize: '20px',
    marginBottom: '15px',
    color: '#333',
  },
  itemEditModalLabel: {
    display: 'block',
    marginBottom: '5px',
    fontWeight: 'bold',
    fontSize: '14px',
    color: '#555',
  },
  itemEditModalInput: {
    width: '100%',
    padding: '8px',
    marginBottom: '15px',
    border: '1px solid #ddd',
    borderRadius: '5px',
    fontSize: '15px',
  },
  itemEditModalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    marginTop: '20px',
  },
  itemEditModalButton: {
    padding: '10px 20px',
    borderRadius: '5px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '16px',
    transition: 'background-color 0.3s ease',
  },
  itemEditModalButtonSave: {
    backgroundColor: '#28a745',
    color: 'white',
  },
  itemEditModalButtonCancel: {
    backgroundColor: '#6c757d',
    color: 'white',
  },
  fixedBottomBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    width: '100%',
    backgroundColor: '#ffffff',
    boxShadow: '0 -2px 8px rgba(0,0,0,0.1)',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: '10px 0',
    zIndex: 400,
    height: '70px',
  },
  fixedBottomBarButton: {
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#888',
    fontSize: '12px',
    transition: 'color 0.2s ease, transform 0.2s ease',
    padding: '5px 0',
  },
  fixedBottomBarButtonActive: {
    color: '#000000',
    transform: 'translateY(-2px)',
    fontWeight: 'bold',
  },
  fixedBottomBarButtonIcon: {
    fontSize: '34px',
    margin: 0,
    lineHeight: '1em',
  },

  // ESTILOS PARA LA LISTA DE PACIENTES TIPO BURBUJA DE MENSAJE (usado en AtencionMedicaPacienteCitadoSeleccionar)
  patientWhatsAppListItem: {
    backgroundColor: '#e9f0f8',
    borderRadius: '15px',
    padding: '8px 15px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    minHeight: '60px',
    boxSizing: 'border-box',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 12px rgba(0,0,0,0.12)',
      backgroundColor: '#dce8f5',
    },
  },
  patientWhatsAppAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '18px',
    fontWeight: 'bold',
    color: 'white',
    flexShrink: 0,
    backgroundColor: '#007bff',
    boxShadow: '0 2px 5px rgba(0,0,0,0.2)',
  },
  patientWhatsAppContent: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    textAlign: 'left',
  },
  patientWhatsAppTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: '2px',
  },
  patientWhatsAppName: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#2c3e50',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flexGrow: 1,
  },
  patientWhatsAppTime: {
    fontSize: '12px',
    color: '#555',
    flexShrink: 0,
    marginLeft: '10px',
  },
  patientWhatsAppDetails: {
    fontSize: '12px',
    color: '#666',
    margin: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    textAlign: 'left',
  },

  bubbleListItemNoAvatar: {
    backgroundColor: '#e9f0f8',
    borderRadius: '15px',
    padding: '8px 15px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    minHeight: '60px',
    boxSizing: 'border-box',
    marginBottom: '8px',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 12px rgba(0,0,0,0.12)',
      backgroundColor: '#dce8f5',
    },
  },
  bubbleContentNoAvatar: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    textAlign: 'left',
  },
  bubbleTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: '2px',
  },
  bubbleName: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#2c3e50',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flexGrow: 1,
    marginRight: '10px',
  },
  bubbleTime: {
    fontSize: '12px',
    color: '#555',
    flexShrink: 0,
    marginLeft: '10px',
  },
  bubbleDetails: {
    fontSize: '12px',
    color: '#666',
    margin: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    textAlign: 'left',
  },
  bubbleActionsTopRight: {
    display: 'flex',
    gap: '4px',
    flexShrink: 0,
  },
  bubbleActionButton: {
    background: 'none',
    border: 'none',
    fontSize: '13px',
    cursor: 'pointer',
    color: '#007bff',
    padding: '4px',
    borderRadius: '5px',
    transition: 'background-color 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:hover': {
      backgroundColor: 'rgba(0,123,255,0.1)',
    },
  },
  bubbleActionButtonDelete: {
    color: '#dc3545',
    '&:hover': {
      backgroundColor: 'rgba(220,53,69,0.1)',
    },
  },
  bubbleActionButtonIcon: {
    width: '18px',
    height: '18px',
  },

  menuTab2Container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    padding: '20px',
    boxSizing: 'border-box',
    backgroundColor: '#ebeff2',
    minHeight: 'calc(100vh - 60px)',
  },
  iconNavigationGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: '20px',
    maxWidth: '800px',
    width: '100%',
    marginBottom: '30px',
    justifyContent: 'center',
  },
  iconNavigationButton: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px 10px',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    border: '1px solid #e0e0e0',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease, border-color 0.2s ease',
    color: '#34495e',
    textDecoration: 'none',
    minHeight: '120px',
  },
  iconNavigationButtonActive: {
    backgroundColor: 'rgba(14, 119, 232, 0.1)',
    borderColor: '#0e77e8',
    boxShadow: '0 6px 15px rgba(14, 119, 232, 0.25)',
    transform: 'translateY(-3px)',
  },
  iconNavigationIconSize: '48px',
  iconNavigationIcon: {
    marginBottom: '10px',
    color: '#0e77e8',
  },
  iconNavigationText: {
    fontSize: '16px',
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: '1.2',
  },
  menuTab2Content: {
    width: '100%',
    maxWidth: '700px',
    backgroundColor: '#ffffff',
    padding: '25px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.06)',
    boxSizing: 'border-box',
  },

  // --- ESTILOS PARA EL COMPONENTE LOGIN ---
  loginContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 'calc(100vh - 60px)', // Resta la altura de la navbar superior
    backgroundColor: '#f0f2f5', // Fondo suave
    padding: '20px',
    boxSizing: 'border-box',
  },
  loginForm: {
    backgroundColor: '#ffffff',
    padding: '40px',
    borderRadius: '12px',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
    maxWidth: '400px',
    textAlign: 'center',
  },
  loginTitle: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#333',
    marginBottom: '10px',
  },
  loginInput: {
    padding: '12px 15px',
    borderRadius: '8px',
    border: '1px solid #e0e0e0',
    fontSize: '16px',
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    '&:focus': {
      borderColor: '#007bff',
      boxShadow: '0 0 0 3px rgba(0, 123, 255, 0.25)',
    },
  },
  loginButton: {
    backgroundColor: '#007bff',
    color: 'white',
    padding: '12px 20px',
    border: 'none',
    borderRadius: '8px',
    fontSize: '18px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
    boxShadow: '0 4px 10px rgba(0, 123, 255, 0.3)',
    '&:hover': {
      backgroundColor: '#0056b3',
      transform: 'translateY(-2px)',
    },
    '&:disabled': {
      backgroundColor: '#cccccc',
      cursor: 'not-allowed',
      boxShadow: 'none',
      transform: 'none',
    },
  },
  loginSignupText: {
    fontSize: '15px',
    color: '#555',
    marginTop: '10px',
  },
  loginSignupLink: {
    color: '#007bff',
    textDecoration: 'none',
    fontWeight: '600',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  // --- FIN ESTILOS PARA EL COMPONENTE LOGIN ---


  '@media (min-width: 769px)': {
    container: {
      maxWidth: '700px',
    },
  },

  '@media (max-width: 768px)': {
    container: {
      paddingLeft: '15px',
      paddingRight: '15px',
      paddingBottom: '80px',
    },
    pageHeader: {
      padding: '6px 15px',
    },
    pageHeaderBackButton: {
      left: '15px',
      fontSize: '24px',
    },
    pageHeaderTitle: {
      fontSize: '20px',
    },
    patientSummaryCard: {
      padding: '6px 15px',
      marginBottom: '15px',
    },
    patientSummaryName: {
      fontSize: '18px',
    },
    patientSummaryDetails: {
      fontSize: '13px',
    },
    medicalSection: {
      padding: '20px',
      marginBottom: '25px',
    },
    textArea: {
      fontSize: '15px',
      minHeight: '70px',
    },
    micButton: {
      width: '50px',
      height: '50px',
      fontSize: '26px',
    },
    micButtonActive: {
      width: '55px',
      height: '55px',
      fontSize: '28px',
    },
    saveButton: {
      padding: '15px 30px',
      fontSize: '18px',
    },
    fixedBottomBar: {
      height: '65px',
      padding: '8px 0',
    },
    fixedBottomBarButton: {
      fontSize: '11px',
      gap: '3px',
    },
    fixedBottomBarButtonIcon: {
      fontSize: '22px',
    },
    patientWhatsAppListItem: {
      padding: '6px 12px',
      minHeight: '55px',
    },
    patientWhatsAppAvatar: {
      width: '35px',
      height: '35px',
      fontSize: '16px',
    },
    patientWhatsAppName: {
      fontSize: '15px',
    },
    patientWhatsAppTime: {
      fontSize: '11px',
    },
    patientWhatsAppDetails: {
      fontSize: '11px',
    },
    bubbleListItemNoAvatar: {
      padding: '6px 12px',
      minHeight: '55px',
    },
    bubbleName: {
      fontSize: '15px',
    },
    bubbleTime: {
      fontSize: '11px',
    },
    bubbleDetails: {
      fontSize: '11px',
    },
    bubbleActionButton: {
      fontSize: '12px',
      padding: '3px 6px',
    },
    bubbleActionButtonIcon: {
      width: '16px',
      height: '16px',
    },
    inputContainer: {
      gap: '10px',
      flexWrap: 'nowrap',
    },
    autocompleteInputWrapper: {
      flexWrap: 'nowrap',
    },
    autocompleteInput: {
      paddingRight: '35px',
    },
    clearInputButton: {
      right: '60px',
    },
    iconNavigationGrid: {
      gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
      gap: '15px',
      marginBottom: '20px',
    },
    iconNavigationButton: {
      padding: '15px 8px',
      minHeight: '100px',
    },
    iconNavigationIconSize: '40px',
    iconNavigationIcon: {
      marginBottom: '8px',
    },
    iconNavigationText: {
      fontSize: '14px',
    },
    menuTab2Content: {
      padding: '20px',
    },
    // Ajustes para Login en móvil
    loginForm: {
      padding: '30px',
      gap: '15px',
    },
    loginTitle: {
      fontSize: '24px',
    },
    loginInput: {
      padding: '10px 12px',
      fontSize: '15px',
    },
    loginButton: {
      padding: '10px 15px',
      fontSize: '16px',
    },
    loginSignupText: {
      fontSize: '14px',
    },
  },

  '@media (max-width: 480px)': {
    container: {
      paddingLeft: '10px',
      paddingRight: '10px',
      paddingBottom: '75px',
    },
    pageHeader: {
      padding: '5px 10px',
    },
    pageHeaderBackButton: {
      left: '10px',
      fontSize: '22px',
    },
    pageHeaderTitle: {
      fontSize: '18px',
    },
    patientSummaryCard: {
      padding: '5px 10px',
      marginBottom: '10px',
    },
    patientSummaryName: {
      fontSize: '16px',
    },
    patientSummaryDetails: {
      fontSize: '12px',
    },
    medicalSection: {
      padding: '15px',
      marginBottom: '20px',
    },
    textArea: {
      fontSize: '14px',
      minHeight: '60px',
    },
    micButton: {
      width: '45px',
      height: '45px',
      fontSize: '24px',
    },
    micButtonActive: {
      width: '50px',
      height: '50px',
      fontSize: '26px',
    },
    saveButton: {
      padding: '12px 25px',
      fontSize: '16px',
    },
    fixedBottomBar: {
      height: '60px',
      padding: '5px 0',
    },
    fixedBottomBarButton: {
      fontSize: '10px',
      gap: '2px',
    },
    fixedBottomBarButtonIcon: {
      fontSize: '20px',
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: '8px',
    },
    autocompleteInputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: '8px',
    },
    autocompleteInput: {
      width: '100%',
    },
    iconNavigationGrid: {
      gridTemplateColumns: 'repeat(auto-fit, minmax(80px, 1fr))',
      gap: '10px',
      marginBottom: '15px',
    },
    iconNavigationButton: {
      padding: '10px 5px',
      minHeight: '80px',
    },
    iconNavigationIconSize: '32px',
    iconNavigationIcon: {
      marginBottom: '5px',
    },
    iconNavigationText: {
      fontSize: '12px',
    },
    menuTab2Content: {
      padding: '15px',
    },
    // Ajustes para Login en móvil muy pequeño
    loginForm: {
      padding: '25px',
      gap: '10px',
    },
    loginTitle: {
      fontSize: '22px',
    },
    loginInput: {
      padding: '8px 10px',
      fontSize: '14px',
    },
    loginButton: {
      padding: '10px 15px',
      fontSize: '15px',
    },
    loginSignupText: {
      fontSize: '13px',
    },
  },

// EMPEZAR AGREGACIÓN DE ESTILOS
loadingOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)', // Fondo blanco semitransparente
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000, // Asegura que esté por encima de todo
    flexDirection: 'column',
    gap: '15px',
 },
    loadingText: {
    fontSize: '18px',
    fontWeight: '500',
    color: '#007bff',
 },
// FINALIZAR AGREGACIÓN DE ESTILOS
 loadingOverlay: {
 position: 'fixed',
 top: 0,
 left: 0,
 right: 0,
 bottom: 0,
 backgroundColor: 'rgba(255, 255, 255, 0.8)', // Fondo blanco semitransparente
 display: 'flex',
 justifyContent: 'center',
 alignItems: 'center',
 zIndex: 2000, // Asegura que esté por encima de todo
 flexDirection: 'column',
 gap: '15px',
},
loadingText: {
 fontSize: '18px',
 fontWeight: '500',
 color: '#007bff',
 },

};

export default Styles;
